import React from 'react'

function LearningPanel({ isActive }) {
  return (
    <section className={isActive ? 'workspace-pane active' : 'workspace-pane'}>
      {/* <div className="learn-hero">
        <h2>Understand how threat detection works</h2>
        <p className="muted">This page explains the models powering the scanner, the explanation signals (SHAP), and the key URL/domain features used to detect phishing. Use this to interpret results and improve your threat-hunting workflows.</p>
      </div> */}

      <div className="learn-grid">
        <article className="learn-card">
          <h4>Models Overview</h4>
          <p className="muted">We ship a small ensemble of models; each has tradeoffs in accuracy, explainability and latency.</p>

          <ul className="learn-list">
            <li>
              <strong>RandomForest</strong> — Robust and accurate on tabular URL features. Good balance of recall/precision.
            </li>
            <li>
              <strong>DecisionTree</strong> — Fast and interpretable; useful for quick rule-like decisions and debugging.
            </li>
            <li>
              <strong>XGBoost</strong> — Gradient-boosted model with strong performance on skewed datasets.
            </li>
            <li>
              <strong>LogisticRegression</strong> — Linear model with probabilistic outputs; easy to calibrate and explain.
            </li>
          </ul>

          <div className="learn-note">
            <strong>Tip:</strong> Use <em>All models</em> mode to compare predictions and check consensus.
          </div>
        </article>

        <article className="learn-card">
          <h4>SHAP Explanations</h4>
          <p className="muted">SHAP values show how each feature contributed to the model's prediction for a single URL. Positive values increase the score toward 'phish', negative toward 'benign'.</p>

          <details>
            <summary style={{ cursor: 'pointer', fontWeight: 700 }}>How to read SHAP output</summary>
            <ul className="learn-list">
              <li><strong>Feature name</strong> — the attribute measured (e.g., <code>url_length</code>).</li>
              <li><strong>Importance</strong> — magnitude of influence for the current prediction (larger = more influence).</li>
              <li><strong>Direction</strong> — whether the feature pushed the model toward phishing or safe.</li>
            </ul>
          </details>

          <p className="muted" style={{ marginTop: 8 }}>
            Example: if <code>has_ip</code> = true and SHAP is strongly positive, the model treats IP-based URLs as more suspicious.
          </p>
        </article>

        <article className="learn-card">
          <h4>Common Phishing Parameters</h4>
          <p className="muted">The scanner uses lexical, host, and content-derived features. Key signals include:</p>

          <ul className="learn-list">
            <li><strong>url_length</strong> — Very long URLs can hide phishing payloads.</li>
            <li><strong>has_ip</strong> — URLs that use raw IP addresses are often malicious.</li>
            <li><strong>num_dots</strong> — Many subdomains or path separators can indicate obfuscation.</li>
            <li><strong>suspicious_tld</strong> — Rare or newly-assigned TLDs are used for abuse.</li>
            <li><strong>entropy</strong> — High character randomness may indicate autogenerated or obfuscated tokens.</li>
            <li><strong>path_depth</strong> — Deep path segments can host malicious resources.
            </li>
            <li><strong>domain_age</strong> — Recently-registered domains are more likely to be malicious.</li>
            <li><strong>has_at_symbol</strong> — The `@` symbol can be used for redirection/tricks.</li>
          </ul>

          <div className="learn-note">
            <strong>Actionable:</strong> Combine SHAP insights with domain reputation and WHOIS checks to triage high-risk URLs.
          </div>
        </article>

        <article className="learn-card">
          <h4>Examples & Case Studies</h4>
          <p className="muted">Below are short examples to help you map features to real-world phishing patterns.</p>

          <details>
            <summary style={{ cursor: 'pointer', fontWeight: 700 }}>Suspicious login page</summary>
            <p className="muted">A URL mimicking a bank login often has a legitimate-looking path but strange subdomain, low domain age, and high probability assigned by models. SHAP typically highlights <code>domain_age</code>, <code>num_dots</code>, and <code>suspicious_tld</code>.</p>
          </details>

          <details>
            <summary style={{ cursor: 'pointer', fontWeight: 700 }}>Shortened / redirectors</summary>
            <p className="muted">Redirector services or shorteners remove context; features like <code>has_redirect</code> (if available) and <code>entropy</code> can be informative. Validate the final landing page when possible.</p>
          </details>
        </article>

        <article className="learn-card full-width">
          <h4>Resources & Next Steps</h4>
          <ul className="learn-list">
            <li>SHAP documentation: https://github.com/slundberg/shap</li>
            <li>Phishing indicators: https://www.us-cert.gov/ncas/tips/ST04-014</li>
            <li>WHOIS & domain reputation checks to correlate with model signals</li>
          </ul>

          <p className="muted">If you'd like, we can add interactive examples that run live from sample URLs and show per-feature SHAP contributions inline.</p>
        </article>
      </div>
    </section>
  )
}

export default LearningPanel
